// <auto-generated />
using System;
using DialogService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DialogService.Database.Migrations
{
    [DbContext(typeof(DialogDbContext))]
    [Migration("20260611183713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app_dialogs")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DialogService.Database.Entities.Chat", b =>
                {
                    b.Property<Guid>("Chat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<string>("Chat_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chat_name");

                    b.Property<DateTime>("Creation_datetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Creator_id")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("Last_update_datetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Chat_id")
                        .HasName("pk_chats");

                    b.ToTable("chats", "app_dialogs");
                });

            modelBuilder.Entity("DialogService.Database.Entities.ChatUser", b =>
                {
                    b.Property<Guid>("Chat_id")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<Guid>("User_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("Creation_datetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Chat_id", "User_id")
                        .HasName("pk_chat_users");

                    b.ToTable("chat_users", "app_dialogs");
                });

            modelBuilder.Entity("DialogService.Database.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Message_id")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("Chat_id")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("Creation_datetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<Guid>("User_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Message_id", "Chat_id")
                        .HasName("pk_messages");

                    b.ToTable("messages", "app_dialogs");
                });
#pragma warning restore 612, 618
        }
    }
}
