// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Database;

#nullable disable

namespace UserService.Database.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app_users")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Database.Entities.FeedOutboxEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Kafka_key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kafka_key");

                    b.Property<string>("Kafka_value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kafka_value");

                    b.Property<DateTime?>("Processed_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_feed_outbox");

                    b.ToTable("feed_outbox", "app_users");
                });

            modelBuilder.Entity("UserService.Database.Entities.FriendEntity", b =>
                {
                    b.Property<Guid>("User_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Friend_id")
                        .HasColumnType("uuid")
                        .HasColumnName("friend_id");

                    b.HasKey("User_id", "Friend_id")
                        .HasName("pk_friends");

                    b.HasIndex("Friend_id")
                        .HasDatabaseName("ix_friends_friend_id");

                    b.ToTable("friends", "app_users");
                });

            modelBuilder.Entity("UserService.Database.Entities.Post", b =>
                {
                    b.Property<Guid>("Post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("Creation_datetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasJsonPropertyName("creation_datetime");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("post")
                        .HasJsonPropertyName("post");

                    b.Property<Guid>("User_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Post_id")
                        .HasName("pk_posts");

                    b.HasIndex("User_id")
                        .HasDatabaseName("posts_userid_idx");

                    b.ToTable("posts", "app_users");
                });

            modelBuilder.Entity("UserService.Database.Entities.User", b =>
                {
                    b.Property<Guid>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("biography");

                    b.Property<string>("Birthdate")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("birthdate");

                    b.Property<bool>("CanPublishMessages")
                        .HasColumnType("boolean")
                        .HasColumnName("can_publish_messages");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Second_name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("second_name");

                    b.HasKey("User_id")
                        .HasName("pk_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("users_login_idx");

                    b.HasIndex("First_name", "Second_name")
                        .HasDatabaseName("users_fname_sname_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("First_name", "Second_name"), "btree");

                    b.ToTable("users", "app_users");
                });

            modelBuilder.Entity("UserService.Database.Entities.FriendEntity", b =>
                {
                    b.HasOne("UserService.Database.Entities.User", "Friend")
                        .WithMany()
                        .HasForeignKey("Friend_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friends_users_friend_id");

                    b.HasOne("UserService.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_friends_users_user_id");

                    b.Navigation("Friend");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
